#!/usr/bin/python3
import sys
import time
import math

"""
File_name: rsa
Created: 21st June, 2023
Auth: Zezetu Sibara
Size: undefined
Project: RSA-Factoring-Challenge
Status: submitted.
"""


def factorization():

    """
    # factorize(int) Factorize all
    # This task is the same as task 0"""
    try:
        files = sys.argv[1]
        with open(files) as f:
            for numbs in f:
                numbs = int(numbs)
                if numbs % 2 == 0:
                    print("{}={}*{}".format(numbs, numbs // 2, 2))
                    continue
                run = 3
                while run < numbs // 2:
                    if numbs % run == 0:
                        print("{}={}*{}".format(numbs, numbs // run, run))
                        break
                    run = run + 2
                if run == (numbs // 2) + 1:
                    print("{}={}*{}".format(numbs, numbs, 1))
    except (IndexError):
        pass


factorization()
